[package]
name = "schnorr-identification-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.6.4"
num-bigint = { version = "0.4.5", features = ["rand"] }
num-primes = "0.3.0"
elliptic-curve = "0.13.8"
p256 = "0.13.2"
rand_core = "0.6.4"
base64 = "0.22.1"
